INSERT INTO "SYSTEM"."USUARIO" (NOMBRE, CORREO_ELECTRONICO, PASS, ROL) VALUES 
('Erick Ramírez', 'erick.ramirez@mail.com', 'admin2024', 'ADMIN');

INSERT INTO "SYSTEM"."USUARIO" (NOMBRE, CORREO_ELECTRONICO, PASS, ROL) VALUES 
('Patricia Morales', 'patricia.morales@mail.com', 'comerciante2024', 'COMERCIANTE');

------------------------------------------------------------------------------------------

INSERT INTO "SYSTEM"."COMERCIANTE" (NOMBRE, MUNICIPIO, TELEFONO, CORREO_ELECTRONICO, FECHA_REGISTRO, ESTADO) VALUES
('Fernando Soto', 'Delicias', '6391200345', 'fernando.soto@mail.com', TO_DATE('2023-02-10','YYYY-MM-DD'), 'ACTIVO');

INSERT INTO "SYSTEM"."COMERCIANTE" (NOMBRE, MUNICIPIO, TELEFONO, CORREO_ELECTRONICO, FECHA_REGISTRO, ESTADO) VALUES
('Gabriela Ruiz', 'Chihuahua', '6143345567', 'gabriela.ruiz@mail.com', TO_DATE('2023-03-15','YYYY-MM-DD'), 'INACTIVO');

INSERT INTO "SYSTEM"."COMERCIANTE" (NOMBRE, MUNICIPIO, TELEFONO, CORREO_ELECTRONICO, FECHA_REGISTRO, ESTADO) VALUES
('Manuel Ortega', 'Juárez', '6562211789', 'manuel.ortega@mail.com', TO_DATE('2023-05-20','YYYY-MM-DD'), 'ACTIVO');

INSERT INTO "SYSTEM"."COMERCIANTE" (NOMBRE, MUNICIPIO, TELEFONO, CORREO_ELECTRONICO, FECHA_REGISTRO, ESTADO) VALUES
('Lucía Esparza', 'Camargo', '6485543321', 'lucia.esparza@mail.com', TO_DATE('2023-07-12','YYYY-MM-DD'), 'ACTIVO');

INSERT INTO "SYSTEM"."COMERCIANTE" (NOMBRE, MUNICIPIO, TELEFONO, CORREO_ELECTRONICO, FECHA_REGISTRO, ESTADO) VALUES
('José Méndez', 'Parral', '6277799123', 'jose.mendez@mail.com', TO_DATE('2023-09-30','YYYY-MM-DD'), 'INACTIVO');

--------------------------------------------------------------------


INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Carnicería El Toro', 42000.00, 4, 1);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Panadería Don Pancho', 38000.50, 3, 2);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Ferretería El Martillo', 61000.00, 5, 3);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Boutique Fashion', 77000.90, 6, 1);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Papelería Escolar', 32000.75, 2, 4);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Supermercado Express', 85000.30, 7, 5);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Tortillería Lupita', 28000.00, 3, 3);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('MiniMarket Los Amigos', 52000.80, 4, 2);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Farmacia Bienestar', 45000.60, 3, 5);

INSERT INTO "SYSTEM"."ESTABLECIMIENTO" (NOMBRE, INGRESOS, NUM_EMPLEADOS, COMERCIANTE_ID) VALUES
('Ferretería Industrial', 68000.20, 5, 4);
