--------------------------------------------------------
-- Archivo creado  - viernes-mayo-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMERCIANTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMERCIANTE" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"MUNICIPIO" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(100 BYTE), 
	"FECHA_REGISTRO" DATE, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"FECHA_ACTUALIZACION" DATE, 
	"USUARIO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTABLECIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESTABLECIMIENTO_PK" ON "SYSTEM"."COMERCIANTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMERCIANTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMERCIANTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COMERCIANTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COMERCIANTE" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COMERCIANTE" ADD CONSTRAINT "ESTABLECIMIENTO_PK" PRIMARY KEY ("ID")
  USING INDEX "SYSTEM"."ESTABLECIMIENTO_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMERCIANTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMERCIANTE" ADD FOREIGN KEY ("USUARIO")
	  REFERENCES "SYSTEM"."USUARIO" ("ID") ENABLE;
