--------------------------------------------------------
-- Archivo creado  - viernes-mayo-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTABLECIMIENTO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTABLECIMIENTO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"INGRESOS" NUMBER(10,2), 
	"NUM_EMPLEADOS" NUMBER, 
	"FECHA_ACTUALIZACION" DATE, 
	"USUARIO" NUMBER, 
	"COMERCIANTE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTABLECIMEINTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESTABLECIMEINTO_PK" ON "SYSTEM"."ESTABLECIMIENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" ADD CONSTRAINT "ESTABLECIMEINTO_PK" PRIMARY KEY ("ID")
  USING INDEX "SYSTEM"."ESTABLECIMEINTO_PK"  ENABLE;
  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" MODIFY ("COMERCIANTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" ADD CONSTRAINT "ESTABLECIMIENTO_FK1" FOREIGN KEY ("COMERCIANTE_ID")
	  REFERENCES "SYSTEM"."COMERCIANTE" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."ESTABLECIMIENTO" ADD FOREIGN KEY ("USUARIO")
	  REFERENCES "SYSTEM"."USUARIO" ("ID") ENABLE;
