CREATE TABLE USERS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100) NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(150) NOT NULL UNIQUE,
    PASS            VARCHAR2(200) NOT NULL,
    ROL             VARCHAR2(50),
    CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED        TIMESTAMP,
    LAST_LOGIN      TIMESTAMP,
    ISACTIVE        NUMBER(1) DEFAULT 1
);



CREATE TABLE PHONES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMBER      VARCHAR2(20) NOT NULL,
    CITYCODE    VARCHAR2(10) NOT NULL,
    CONTRYCODE  VARCHAR2(10) NOT NULL,
    USER_ID     NUMBER NOT NULL,
    
    CONSTRAINT FK_PHONES_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE CASCADE
);


CREATE TABLE ROLES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR2(200)
);


CREATE TABLE TOKENS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN       VARCHAR2(500) NOT NULL,
    TOKEN_TYPE  VARCHAR2(20) NOT NULL,
    IS_EXPIRED  NUMBER(1) DEFAULT 0,
    IS_REVOKED  NUMBER(1) DEFAULT 0,
    USER_ID     NUMBER NOT NULL,

    CONSTRAINT FK_TOKEN_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE CASCADE
);


CREATE INDEX IDX_USER_EMAIL ON USERS (CORREO_ELECTRONICO);

CREATE INDEX IDX_TOKENS_USER ON TOKENS (USER_ID);

CREATE INDEX IDX_PHONES_USER ON PHONES (USER_ID);
